### ISSUE TITLE
ideas/todo

### ISSUE THREAD

**Issue by ckampfe** [ckampfe/cbuf#1]
- [x] typespecs
- [x] implementation as `Map`
- [x] implementation as `ETS`
- [x] benchmark the above
- [x] make into a protocol and implement backends rather than concrete `array`-based implementation

**Comment by ckampfe** [comment]
https://github.com/ckampfe/cbuf/commit/44d8a04495cd2745be5d358f9f1bc6e9cff57a42
